version: "3"
services:
  #mssql docker
  carwash-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=PZPpzp123!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - carwashnet

  # carwash-api:
  #   restart: unless-stopped
  #   build:
  #     context: .
  #   environment:
  #     - ConnectionStrings:carwashDb=Server=carwash-sql,1433;Database=Carwash;User=sa;Password=PZPpzp123!;ConnectRetryCount=0
  #   ports:
  #     - 5013:80
  #   networks:
  #     - carwashnet
  #   links:
  #     - carwash-sql
  #   depends_on:
  #     - carwash-sql

networks:
  carwashnet:
    driver: bridge
